# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='autor',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='libros',
            old_name='editorial',
            new_name='Editorial',
        ),
        migrations.RenameField(
            model_name='libros',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='libros',
            old_name='precio',
            new_name='Precio',
        ),
    ]
